# Workflow Name: Describes the purpose of the pipeline
name: Build and Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the workflow on push events to the main branch
  pull_request:
    branches:
      - main # Also triggers on pull requests to main for validation

jobs:
  # Job to build and deploy the site
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # Runs on a virtual machine hosted by GitHub
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Build Static Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4